AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable


Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Layout/EmptyLineBetweenDefs:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'